repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace    # Entfernt unnötige Leerzeichen
      - id: end-of-file-fixer      # Fügt eine neue Zeile am Ende der Datei hinzu
      - id: check-added-large-files  # Warnung bei großen Dateien
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint           # Linting für Markdown-Dateien (README.md)
 

 #Prettier gibt es nicht mehr gratis zum verrwenden